<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    private const TABLE = 'password_reset_tokens';

    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create(self::TABLE, function (Blueprint $table): void {

            $table->string('email', 150)
                ->primary()
                ->comment('User email requesting password reset');

            $table->string('token', 255)
                ->comment('Secure password reset token generated by Laravel');

            $table->timestamp('created_at')
                ->nullable()
                ->comment('Timestamp when the reset token was generated');

            /*
             |--------------------------------------------------------------------------
             | Indexes
             |--------------------------------------------------------------------------
             */

            $table->index(
                'created_at',
                'password_reset_tokens_created_at_idx'
            );
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists(self::TABLE);
    }
};